version: '3.9'

services:
  postgres-16:
    image: postgres:16
    container_name: postgres-16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hexagonal_go_grpc
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - "${OTEL_CONFIG_PATH}:/etc/otel-collector-config.yaml"
    ports:
      - "4317:4317" # OTLP gRPC receiver

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - "${PROMETHEUS_CONFIG_PATH}:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  hexagonal-go-grpc:
    build: .
    container_name: hexagonal-go-grpc
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - otel-collector
      - postgres-16

volumes:
  postgres_data:
