// Code generated by mockery v2.53.3. DO NOT EDIT.

package service

import (
	context "context"
	entity "hexagonal-go-grpc/internal/adapters/service/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockICustomerService is an autogenerated mock type for the ICustomerService type
type MockICustomerService struct {
	mock.Mock
}

type MockICustomerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICustomerService) EXPECT() *MockICustomerService_Expecter {
	return &MockICustomerService_Expecter{mock: &_m.Mock}
}

// ActivateById provides a mock function with given fields: ctx, request
func (_m *MockICustomerService) ActivateById(ctx context.Context, request entity.CustomerIdRequest) (entity.Customer, int, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ActivateById")
	}

	var r0 entity.Customer
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerIdRequest) (entity.Customer, int, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerIdRequest) entity.Customer); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(entity.Customer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CustomerIdRequest) int); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.CustomerIdRequest) error); ok {
		r2 = rf(ctx, request)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICustomerService_ActivateById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateById'
type MockICustomerService_ActivateById_Call struct {
	*mock.Call
}

// ActivateById is a helper method to define mock.On call
//   - ctx context.Context
//   - request entity.CustomerIdRequest
func (_e *MockICustomerService_Expecter) ActivateById(ctx interface{}, request interface{}) *MockICustomerService_ActivateById_Call {
	return &MockICustomerService_ActivateById_Call{Call: _e.mock.On("ActivateById", ctx, request)}
}

func (_c *MockICustomerService_ActivateById_Call) Run(run func(ctx context.Context, request entity.CustomerIdRequest)) *MockICustomerService_ActivateById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CustomerIdRequest))
	})
	return _c
}

func (_c *MockICustomerService_ActivateById_Call) Return(_a0 entity.Customer, _a1 int, _a2 error) *MockICustomerService_ActivateById_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICustomerService_ActivateById_Call) RunAndReturn(run func(context.Context, entity.CustomerIdRequest) (entity.Customer, int, error)) *MockICustomerService_ActivateById_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, request
func (_m *MockICustomerService) Create(ctx context.Context, request entity.CustomerCreateRequest) (entity.Customer, int, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Customer
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerCreateRequest) (entity.Customer, int, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerCreateRequest) entity.Customer); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(entity.Customer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CustomerCreateRequest) int); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.CustomerCreateRequest) error); ok {
		r2 = rf(ctx, request)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICustomerService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockICustomerService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request entity.CustomerCreateRequest
func (_e *MockICustomerService_Expecter) Create(ctx interface{}, request interface{}) *MockICustomerService_Create_Call {
	return &MockICustomerService_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockICustomerService_Create_Call) Run(run func(ctx context.Context, request entity.CustomerCreateRequest)) *MockICustomerService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CustomerCreateRequest))
	})
	return _c
}

func (_c *MockICustomerService_Create_Call) Return(_a0 entity.Customer, _a1 int, _a2 error) *MockICustomerService_Create_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICustomerService_Create_Call) RunAndReturn(run func(context.Context, entity.CustomerCreateRequest) (entity.Customer, int, error)) *MockICustomerService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateById provides a mock function with given fields: ctx, request
func (_m *MockICustomerService) DeactivateById(ctx context.Context, request entity.CustomerIdRequest) (entity.Customer, int, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateById")
	}

	var r0 entity.Customer
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerIdRequest) (entity.Customer, int, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerIdRequest) entity.Customer); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(entity.Customer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CustomerIdRequest) int); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.CustomerIdRequest) error); ok {
		r2 = rf(ctx, request)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICustomerService_DeactivateById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateById'
type MockICustomerService_DeactivateById_Call struct {
	*mock.Call
}

// DeactivateById is a helper method to define mock.On call
//   - ctx context.Context
//   - request entity.CustomerIdRequest
func (_e *MockICustomerService_Expecter) DeactivateById(ctx interface{}, request interface{}) *MockICustomerService_DeactivateById_Call {
	return &MockICustomerService_DeactivateById_Call{Call: _e.mock.On("DeactivateById", ctx, request)}
}

func (_c *MockICustomerService_DeactivateById_Call) Run(run func(ctx context.Context, request entity.CustomerIdRequest)) *MockICustomerService_DeactivateById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CustomerIdRequest))
	})
	return _c
}

func (_c *MockICustomerService_DeactivateById_Call) Return(_a0 entity.Customer, _a1 int, _a2 error) *MockICustomerService_DeactivateById_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICustomerService_DeactivateById_Call) RunAndReturn(run func(context.Context, entity.CustomerIdRequest) (entity.Customer, int, error)) *MockICustomerService_DeactivateById_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteById provides a mock function with given fields: ctx, request
func (_m *MockICustomerService) DeleteById(ctx context.Context, request entity.CustomerIdRequest) (int, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerIdRequest) (int, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerIdRequest) int); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CustomerIdRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICustomerService_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockICustomerService_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - ctx context.Context
//   - request entity.CustomerIdRequest
func (_e *MockICustomerService_Expecter) DeleteById(ctx interface{}, request interface{}) *MockICustomerService_DeleteById_Call {
	return &MockICustomerService_DeleteById_Call{Call: _e.mock.On("DeleteById", ctx, request)}
}

func (_c *MockICustomerService_DeleteById_Call) Run(run func(ctx context.Context, request entity.CustomerIdRequest)) *MockICustomerService_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CustomerIdRequest))
	})
	return _c
}

func (_c *MockICustomerService_DeleteById_Call) Return(_a0 int, _a1 error) *MockICustomerService_DeleteById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICustomerService_DeleteById_Call) RunAndReturn(run func(context.Context, entity.CustomerIdRequest) (int, error)) *MockICustomerService_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: ctx, request
func (_m *MockICustomerService) GetById(ctx context.Context, request entity.CustomerIdRequest) (entity.Customer, int, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 entity.Customer
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerIdRequest) (entity.Customer, int, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerIdRequest) entity.Customer); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(entity.Customer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CustomerIdRequest) int); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.CustomerIdRequest) error); ok {
		r2 = rf(ctx, request)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICustomerService_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockICustomerService_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - request entity.CustomerIdRequest
func (_e *MockICustomerService_Expecter) GetById(ctx interface{}, request interface{}) *MockICustomerService_GetById_Call {
	return &MockICustomerService_GetById_Call{Call: _e.mock.On("GetById", ctx, request)}
}

func (_c *MockICustomerService_GetById_Call) Run(run func(ctx context.Context, request entity.CustomerIdRequest)) *MockICustomerService_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CustomerIdRequest))
	})
	return _c
}

func (_c *MockICustomerService_GetById_Call) Return(_a0 entity.Customer, _a1 int, _a2 error) *MockICustomerService_GetById_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICustomerService_GetById_Call) RunAndReturn(run func(context.Context, entity.CustomerIdRequest) (entity.Customer, int, error)) *MockICustomerService_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function with given fields: ctx, request
func (_m *MockICustomerService) GetList(ctx context.Context, request entity.CustomerListRequest) ([]entity.Customer, int, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []entity.Customer
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerListRequest) ([]entity.Customer, int, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerListRequest) []entity.Customer); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CustomerListRequest) int); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.CustomerListRequest) error); ok {
		r2 = rf(ctx, request)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICustomerService_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type MockICustomerService_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - ctx context.Context
//   - request entity.CustomerListRequest
func (_e *MockICustomerService_Expecter) GetList(ctx interface{}, request interface{}) *MockICustomerService_GetList_Call {
	return &MockICustomerService_GetList_Call{Call: _e.mock.On("GetList", ctx, request)}
}

func (_c *MockICustomerService_GetList_Call) Run(run func(ctx context.Context, request entity.CustomerListRequest)) *MockICustomerService_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CustomerListRequest))
	})
	return _c
}

func (_c *MockICustomerService_GetList_Call) Return(_a0 []entity.Customer, _a1 int, _a2 error) *MockICustomerService_GetList_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICustomerService_GetList_Call) RunAndReturn(run func(context.Context, entity.CustomerListRequest) ([]entity.Customer, int, error)) *MockICustomerService_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, request
func (_m *MockICustomerService) Register(ctx context.Context, request entity.CustomerRegisterRequest) (entity.Customer, int, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 entity.Customer
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerRegisterRequest) (entity.Customer, int, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerRegisterRequest) entity.Customer); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(entity.Customer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CustomerRegisterRequest) int); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.CustomerRegisterRequest) error); ok {
		r2 = rf(ctx, request)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICustomerService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockICustomerService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - request entity.CustomerRegisterRequest
func (_e *MockICustomerService_Expecter) Register(ctx interface{}, request interface{}) *MockICustomerService_Register_Call {
	return &MockICustomerService_Register_Call{Call: _e.mock.On("Register", ctx, request)}
}

func (_c *MockICustomerService_Register_Call) Run(run func(ctx context.Context, request entity.CustomerRegisterRequest)) *MockICustomerService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CustomerRegisterRequest))
	})
	return _c
}

func (_c *MockICustomerService_Register_Call) Return(_a0 entity.Customer, _a1 int, _a2 error) *MockICustomerService_Register_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICustomerService_Register_Call) RunAndReturn(run func(context.Context, entity.CustomerRegisterRequest) (entity.Customer, int, error)) *MockICustomerService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, request
func (_m *MockICustomerService) Update(ctx context.Context, request entity.CustomerUpdateRequest) (entity.Customer, int, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entity.Customer
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerUpdateRequest) (entity.Customer, int, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CustomerUpdateRequest) entity.Customer); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(entity.Customer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CustomerUpdateRequest) int); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.CustomerUpdateRequest) error); ok {
		r2 = rf(ctx, request)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICustomerService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockICustomerService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - request entity.CustomerUpdateRequest
func (_e *MockICustomerService_Expecter) Update(ctx interface{}, request interface{}) *MockICustomerService_Update_Call {
	return &MockICustomerService_Update_Call{Call: _e.mock.On("Update", ctx, request)}
}

func (_c *MockICustomerService_Update_Call) Run(run func(ctx context.Context, request entity.CustomerUpdateRequest)) *MockICustomerService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CustomerUpdateRequest))
	})
	return _c
}

func (_c *MockICustomerService_Update_Call) Return(_a0 entity.Customer, _a1 int, _a2 error) *MockICustomerService_Update_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICustomerService_Update_Call) RunAndReturn(run func(context.Context, entity.CustomerUpdateRequest) (entity.Customer, int, error)) *MockICustomerService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICustomerService creates a new instance of MockICustomerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICustomerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICustomerService {
	mock := &MockICustomerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
